# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\sammu\Dropbox\UFOP\Aulas\Calculo Numerico\TP\graphic_interface\Graphic_interface_Qt\grapic_interface.ui',
# licensing of 'C:\Users\sammu\Dropbox\UFOP\Aulas\Calculo Numerico\TP\graphic_interface\Graphic_interface_Qt\grapic_interface.ui' applies.
#
# Created: Tue Jul  2 00:58:47 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_background(object):
    def setupUi(self, background):
        background.setObjectName("background")
        background.setEnabled(True)
        background.resize(437, 491)
        background.setMinimumSize(QtCore.QSize(437, 440))
        background.setMaximumSize(QtCore.QSize(437, 6000000))
        background.setAutoFillBackground(False)
        background.setStyleSheet("")
        self.PB_result = QtWidgets.QPushButton(background)
        self.PB_result.setGeometry(QtCore.QRect(170, 330, 91, 31))
        self.PB_result.setObjectName("PB_result")
        self.RB_trapezium = QtWidgets.QRadioButton(background)
        self.RB_trapezium.setGeometry(QtCore.QRect(20, 290, 111, 31))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.RB_trapezium.setFont(font)
        self.RB_trapezium.setObjectName("RB_trapezium")
        self.Up_line = QtWidgets.QLineEdit(background)
        self.Up_line.setGeometry(QtCore.QRect(290, 100, 121, 31))
        self.Up_line.setAlignment(QtCore.Qt.AlignCenter)
        self.Up_line.setObjectName("Up_line")
        self.Lw_line = QtWidgets.QLineEdit(background)
        self.Lw_line.setGeometry(QtCore.QRect(290, 40, 121, 31))
        self.Lw_line.setAlignment(QtCore.Qt.AlignCenter)
        self.Lw_line.setObjectName("Lw_line")
        self.Sub_line = QtWidgets.QLineEdit(background)
        self.Sub_line.setGeometry(QtCore.QRect(290, 160, 121, 31))
        self.Sub_line.setAlignment(QtCore.Qt.AlignCenter)
        self.Sub_line.setObjectName("Sub_line")
        self.Eqt_line = QtWidgets.QLineEdit(background)
        self.Eqt_line.setGeometry(QtCore.QRect(20, 240, 391, 31))
        self.Eqt_line.setAlignment(QtCore.Qt.AlignCenter)
        self.Eqt_line.setObjectName("Eqt_line")
        self.RB_Sone = QtWidgets.QRadioButton(background)
        self.RB_Sone.setGeometry(QtCore.QRect(150, 290, 141, 31))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.RB_Sone.setFont(font)
        self.RB_Sone.setObjectName("RB_Sone")
        self.RB_Stwo = QtWidgets.QRadioButton(background)
        self.RB_Stwo.setGeometry(QtCore.QRect(290, 290, 131, 31))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.RB_Stwo.setFont(font)
        self.RB_Stwo.setObjectName("RB_Stwo")
        self.Upper_label = QtWidgets.QLabel(background)
        self.Upper_label.setGeometry(QtCore.QRect(110, 100, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.Upper_label.setFont(font)
        self.Upper_label.setTextFormat(QtCore.Qt.RichText)
        self.Upper_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Upper_label.setObjectName("Upper_label")
        self.Lower_label = QtWidgets.QLabel(background)
        self.Lower_label.setGeometry(QtCore.QRect(110, 40, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.Lower_label.setFont(font)
        self.Lower_label.setTextFormat(QtCore.Qt.RichText)
        self.Lower_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Lower_label.setObjectName("Lower_label")
        self.SubIT_label = QtWidgets.QLabel(background)
        self.SubIT_label.setGeometry(QtCore.QRect(110, 160, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.SubIT_label.setFont(font)
        self.SubIT_label.setTextFormat(QtCore.Qt.RichText)
        self.SubIT_label.setAlignment(QtCore.Qt.AlignCenter)
        self.SubIT_label.setObjectName("SubIT_label")
        self.Equation_label = QtWidgets.QLabel(background)
        self.Equation_label.setGeometry(QtCore.QRect(140, 210, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.Equation_label.setFont(font)
        self.Equation_label.setTextFormat(QtCore.Qt.RichText)
        self.Equation_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Equation_label.setObjectName("Equation_label")
        self.Answer = QtWidgets.QLabel(background)
        self.Answer.setGeometry(QtCore.QRect(30, 380, 381, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.Answer.setFont(font)
        self.Answer.setText("")
        self.Answer.setAlignment(QtCore.Qt.AlignCenter)
        self.Answer.setObjectName("Answer")

        self.retranslateUi(background)
        QtCore.QMetaObject.connectSlotsByName(background)

    def retranslateUi(self, background):
        background.setWindowTitle(QtWidgets.QApplication.translate("background", "Akademiet", None, -1))
        self.PB_result.setText(QtWidgets.QApplication.translate("background", "Get Result", None, -1))
        self.RB_trapezium.setText(QtWidgets.QApplication.translate("background", "Trapezium Rule", None, -1))
        self.RB_Sone.setText(QtWidgets.QApplication.translate("background", "1º Simpson\'s Rule", None, -1))
        self.RB_Stwo.setText(QtWidgets.QApplication.translate("background", "2º Simpson\'s Rule", None, -1))
        self.Upper_label.setText(QtWidgets.QApplication.translate("background", "Upper Bound Limit", None, -1))
        self.Lower_label.setText(QtWidgets.QApplication.translate("background", "Lower Bound Limit", None, -1))
        self.SubIT_label.setText(QtWidgets.QApplication.translate("background", "Sub - Intervals", None, -1))
        self.Equation_label.setText(QtWidgets.QApplication.translate("background", "Equation", None, -1))

import images_rc
